title: Copenhagen Coaching Center
description: Vi tilbyder åbne uddannelser, lederuddannelser, konsulentydelser, ledelsessparring, samt coachingsamtaler til private og offentlige virksomheder.
author: Copenhagencoaching.dk
paginate: 24
url: https://www.copenhagencoaching.dk
paginate_path: "/stories/title/"
stage_site: https://stage.copenhagencoaching.dk
prod_site: https://www.copenhagencoaching.dk
image: /images/seo/ccc-seo-logo-dark.png
future: true

logo: /images/logo/ccc-logo-dark.png

whitelist:
  - jekyll-redirect-from

sass:
  style: compressed

highlighter: rouge
exclude:
  - "*README.md"
  - gulpfile.js
  - LICENSE
  - .sass-cache/
timezone: Europe/Copenhagen
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from

themes:
  - title: ledelsesudvikling
    order: 1
    name: Ledelsesudvikling
  - title: organisationsudvikling
    order: 2
    name: Organisationsudvikling
  - title: teamudvikling
    order: 3
    name: Teamudvikling
  - title: procesledelse
    order: 4
    name: Procesledelse
  - title: procesogtest
    order: 5
    name: Ansættelsesproces og testværktøjer
    
consultation-categories:
  - title: Fagområder
    order: 1
  - title: Vores tilgang
    order: 2
  - title: Vores medarbejdere
    order: 3
  - title: Vores værdigrundlag
    order: 4
  - title: Eksempler på aktiviteter
    order: 5
  - title: Praktisk
    order: 6
  - title: Samarbejdspartnerer
    order: 7

customer-categories:
  - title: sundhed & omsorg
    order: 1
  - title: børn & unge
    order: 2
  - title: kultur & forlystelse
    order: 3
  - title: sport & fritid
    order: 4

collections:
  posts:
    output: true
    permalink: /inspiration/:title/
  advisory-board:
    output: false
  employees:
    output: true
    permalink: /employees/:title/
  educations:
    output: true
    permalink: /academy/:title/
  coachings:
    output: true
    permalink: /coaching/:title/
  consultations:
    output: true
    permalink: /consultations/:title/
  internationals:
    output: true
    permalink: /internationals/:title/
  fundament:
    output: true
    permalink: /fundament/:title/
  pages:
    output: true
    permalink: /:title/
  popups:
    output: true
    permalink: /popups/:title/
  texts:
    output: true
    permalink: /tekster/:title/
  pfp-sites:
    output: true
    permalink: /pfp/:title/
  pip-contributors:
    output: true
    permalink: /protrptik-som-behandlingsform-og-ledelsesdisciplin/bidragsydere/:title/
  tests:
    output: true
    permalink: /:title/
  testimonials:
    output: false
  edu-categories:
    output: true
    permalink: /:title/
  calendar:
    output: true
    permalink: /:title/

defaults:
  -
    scope:
      type: posts
    values:
      layout: story
  -
    scope:
      type: employees
    values:
      layout: employee
  -
    scope:
      type: educations
    values:
      layout: education
  -
    scope:
      type: coachings
    values:
      layout: coaching
  -
    scope:
      type: consultations
    values:
      layout: consulting
  -
    scope:
      type: fundament
    values:
      layout: fundament
  -
    scope:
      type: internationals
    values:
      layout: international
  -
    scope:
      type: text
    values:
      layout: default
  -
    scope:
      type: pfp-site
    values:
      layout: pfp-info
  -
    scope:
      type: pip-contributors
    values:
      layout: pip-contributors
  -
    scope:
      type: tests
    values:
      layout: default
  -
    scope:
      type: edu-categories
    values:
      layout: default
  -
    scope:
      type: calendar
    values:
      layout: default

prose:
  rooturl: ''
  siteurl: 'www.copenhagencoaching.dk'
  relativeLinks: ''
  media: 'img/blog'
  ignore:
    - htmlproofer.sh
    - index.html
    - /portraits
    - robots.txt
    - favicon.ico
    - README.md
    - _dev_config.yml
    - _stage_config.yml
    - CNAME
    - CNAME.stage
    - devserve.sh
    - .gitignore
    - /img
    - /_pages/search.html
    - /_pages/studieportal.html
    - _config.yml
    - /_layouts
    - /_includes
    - /pdfs
    - /images
    - .circleci
    - /css
    - /js
    - /_sass
    - /_categories
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "image"
        field:
          element: "text"
          label: "Billed"
      - name: "teaser"
        field:
          element: "text"
          label: "teaser"
          help: "Max 45 anslag"
      - name: "author"
        field:
          element: "select"
          label: "Vælg forfatter"
          placeholder: "Forfatter"
          options:
            - name: "Lars Nyborg"
              value: "Lars Nyborg"
            - name: "Andreas Bering"
              value: "Andreas Bering"
            - name: "Anni Rosengren Korsbæk"
              value: "Anni Rosengren Korsbæk"
            - name: "Bianca Olivia Godske Røjbæk"
              value: "Bianca Olivia Godske Røjbæk"
            - name: "Frederikke Winther"
              value: "Frederikke Winther"
            - name: "Kim Gørtz"
              value: "Kim Gørtz"
            - name: "Marie Arnbak"
              value: "Marie Arnbak"
            - name: "Mette Mejhede"
              value: "Mette Mejhede"
            - name: "Morten Bertelsen"
              value: "Morten Bertelsen"
            - name: "Morten Paustian"
              value: "Morten Paustian"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Tilføj tags"
          placeholder: "Tag"
          alterable: true
          options:
            - name: "Coaching"
              value: "coaching"
            - name: "Ledelse"
              value: "ledelse"
            - name: "Events"
              value: "events"
            - name: "Kurser"
              value: "kurser"
    _educations:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "header"
        field:
          element: "text"
          label: "Header tekst"
          help: "Overskriften i headeren"
      - name: "price"
        field:
          element: "text"
          label: "Pris"
      - name: "event-title"
        field:
          element: "text"
          label: "Begivenheds overkrift"
          help: "Kommende hold eller kommende rejser osv."
      - name: "special"
        field:
          element: "checkbox"
          label: "Skræddersyet uddannelse?"
      - name: "image"
        field:
          element: "text"
          label: "Billed"
      - name: "pdf"
        field:
          element: "text"
          label: "Pdf"
          help: "Hvis der ikke er en pdf og ikke skal være nogen pdf knap skal der stå 'false'"
      - name: "location"
        field:
          element: "text"
          label: "Lokation"
      - name: "description"
        field:
          element: "text"
          label: "Header tekst"
          help: "Teksten der står under overskriften i headeren"
      - name: "contact-person"
        field:
          element: "select"
          label: "Vælg kontaktperson"
          placeholder: "kontaktperson"
          options:
            - name: "Lars Nyborg"
              value: "5"
            - name: "Andreas Bering"
              value: "9"
            - name: "Anni Rosengren Korsbæk"
              value: "8"
            - name: "Frederikke Winther"
              value: "7"
            - name: "Kim Gørtz"
              value: "6"
            - name: "Marie Arnbak"
              value: "4"
            - name: "Mette Mejhede"
              value: "3"
            - name: "Morten Bertelsen"
              value: "1"
            - name: "Morten Paustian"
              value: "2"
    _employees:
      - name: "title"
        field:
          element: "text"
          label: "Navn"
      - name: "portrait-image"
        field:
          element: "text"
          label: "Billed"
      - name: "email"
        field:
          element: "text"
          label: "Email"
      - name: "call"
        field:
          element: "text"
          label: "Tlf."
      - name: "description"
        field:
          element: "text"
          label: "Stilling"
      - name: "linkedin"
        field:
          element: "text"
          label: "LinkedIn profil"
      - name: "order"
        field:
          element: "number"
          type: "number"
          label: "Rækkefølge"
    _consultations:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "order"
        field:
          element: "number"
          type: "number"
          label: "Rækkefølge"
      - name: "image"
        field:
          element: "text"
          label: "Billed"
      - name: "contact-person"
        field:
          element: "select"
          label: "Vælg kontaktperson"
          placeholder: "kontaktperson"
          options:
            - name: "Lars Nyborg"
              value: "5"
            - name: "Andreas Bering"
              value: "9"
            - name: "Anni Rosengren Korsbæk"
              value: "8"
            - name: "Frederikke Winther"
              value: "7"
            - name: "Kim Gørtz"
              value: "6"
            - name: "Marie Arnbak"
              value: "4"
            - name: "Mette Mejhede"
              value: "3"
            - name: "Morten Bertelsen"
              value: "1"
            - name: "Morten Paustian"
              value: "2"
    _conversations:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "order"
        field:
          element: "number"
          type: "number"
          label: "Rækkefølge"
      - name: "image"
        field:
          element: "text"
          label: "Billed"
      - name: "contact-person"
        field:
          element: "select"
          label: "Vælg kontaktperson"
          placeholder: "kontaktperson"
          options:
            - name: "Lars Nyborg"
              value: "5"
            - name: "Andreas Bering"
              value: "9"
            - name: "Anni Rosengren Korsbæk"
              value: "8"
            - name: "Frederikke Winther"
              value: "7"
            - name: "Kim Gørtz"
              value: "6"
            - name: "Marie Arnbak"
              value: "4"
            - name: "Mette Mejhede"
              value: "3"
            - name: "Morten Bertelsen"
              value: "1"
            - name: "Morten Paustian"
              value: "2"
    _internationals:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "order"
        field:
          element: "number"
          type: "number"
          label: "Rækkefølge"
      - name: "image"
        field:
          element: "text"
          label: "Billed"
      - name: "contact-person"
        field:
          element: "select"
          label: "Vælg kontaktperson"
          placeholder: "kontaktperson"
          options:
            - name: "Lars Nyborg"
              value: "5"
            - name: "Andreas Bering"
              value: "9"
            - name: "Anni Rosengren Korsbæk"
              value: "8"
            - name: "Frederikke Winther"
              value: "7"
            - name: "Kim Gørtz"
              value: "6"
            - name: "Marie Arnbak"
              value: "4"
            - name: "Mette Mejhede"
              value: "3"
            - name: "Morten Bertelsen"
              value: "1"
            - name: "Morten Paustian"
              value: "2"
    _fundament:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "order"
        field:
          element: "number"
          type: "number"
          label: "Rækkefølge"
      - name: "image"
        field:
          element: "text"
          label: "Billed"
      - name: "header"
        field:
          element: "text"
          label: "Header tekst"
          help: "Overskriften i headeren"
    _texts:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "link"
        field:
          element: "text"
          label: "Url"
          help: "Hvis der er et link relateret til teksten skal du skrive url'en her"
      - name: "link-text"
        field:
          element: "text"
          label: "Link tekst"
          help: "Hvis der er et link relateret til teksten skal du skrive teksten til linket her"
    _pages:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "show"
        field:
          element: "checkbox"
          label: "Vis i menuen"
          help: "Skal siden linkes fra menuen?"
      - name: "order"
        field:
          element: "number"
          label: "Rækkefølge"
          help: "Hvis siden skal linkes fra menuen hvilket nr i rækkefølgen skal siden være?"
      - name: "image"
        field:
          element: "text"
          label: "Billed"
          help: "Billedstien"
      - name: "header"
        field:
          element: "text"
          label: "Header tekst"
          help: "Overskriften i headeren"
      - name: "header-link"
        field:
          element: "text"
          label: "Header link tekst"
          help: "Teksten til det link der er i headeren"
      - name: "header-link-url"
        field:
          element: "text"
          label: "Adressen til linket"
          help: "Du kan linke til et bestemt sted på siden ved hjælp af hashtag, f.eks #team. Eller du kan linke til en side f.eks. /academy/"
      - name: "description"
        field:
          element: "text"
          label: "Header tekst"
          help: "Teksten der står under overskriften i headeren"
  




responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 255
    - width: 510
    - width: 1020
    - width: 1800

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/responsive/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - images/*/*.{jpeg,jpg,png}
