title: Copenhagen Coaching Center - Coaching og uddannelse af ledere 
description: CCC tilbyder coaching og uddannelser målrettet det offentlige Danmark og erhvervslivet. Se vores mange tilbud om efteruddannelser og coachingløsninger her.
author: Copenhagencoaching.dk
paginate: 24
url: https://www.copenhagencoaching.dk
paginate_path: "/stories/title/"
stage_site: https://stage.copenhagencoaching.dk
prod_site: https://www.copenhagencoaching.dk
image: /images/seo/ccc-seo-logo-dark.png
future: true

logo: /images/logo/ccc-logo-dark.png

whitelist:
  - jekyll-redirect-from

sass:
  style: compressed

highlighter: rouge
exclude:
  - "*README.md"
  - gulpfile.js
  - LICENSE
  - .sass-cache/
timezone: Europe/Copenhagen
markdown: kramdown
permalink: /:categories/:title/

collections:
  posts:
    output: true
    permalink: /resonans/:categories/:title/
  employees:
    output: true
    permalink: /employees/:title/
  educations:
    output: true
    permalink: /academy/:title/
  coachings:
    output: true
    permalink: /coaching/:title/
  internationals:
    output: true
    permalink: /internationals/:title/
  fundament:
    output: true
    permalink: /fundament/:title/
  pages:
    output: true
    permalink: /:title/
  texts:
    output: true
    permalink: /tekster/:title/
  pfp-sites:
    output: true
    permalink: /pfp/:title/
  pip-contributors:
    output: true
    permalink: /protrptik-som-behandlingsform-og-ledelsesdisciplin/bidragsydere/:title/
  testimonials:
    output: false
  edu-categories:
    output: true
    permalink: /:title/
  publications:
    output: true
    permalink: /ousia/:title/
  pfp:
    output: false
    permalink: /:title/
  landings:
    output: true
    permalink: /:title/
  consultings:
    output: true
    permalink: /konsulentydelser/:title/

defaults:
  -
    scope:
      type: posts
    values:
      layout: story
  -
    scope:
      type: employees
    values:
      layout: employee
  -
    scope:
      type: educations
    values:
      layout: education
  -
    scope:
      type: coachings
    values:
      layout: coaching
  -
    scope:
      type: consultations
    values:
      layout: service
  -
    scope:
      type: fundament
    values:
      layout: fundament
  -
    scope:
      type: internationals
    values:
      layout: international
  -
    scope:
      type: text
    values:
      layout: default
  -
    scope:
      type: pfp-site
    values:
      layout: pfp-info
  -
    scope:
      type: pip-contributors
    values:
      layout: pip-contributors
  -
    scope:
      type: edu-categories
    values:
      layout: default
  -
    scope:
      type: publications
    values:
      layout: page
  -
    scope:
      type: pfp
    values:
      layout: page
  -
    scope:
      type: landings
    values:
      layout: landing
  -
    scope:
      type: consultings
    values:
      layout: page



responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 255
    - width: 510
    - width: 1020
    - width: 1800

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/responsive/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
  - /images/{.jpeg}
