title: Copenhagencoaching.dk
description: 'Copenhagen Coaching Center'
author: Prolike
url: https:/www.copenhagencoaching.dk
paginate: 24
paginate_path: "/stories/page:num/"

logo: /img/seo_img.png

social:
  name: Prolike
  links: https://www.linkedin.com/company/prolike/

sass:
  style: compressed

highlighter: rouge
exclude:
  - "*README.md"
  - bower_components
  - node_modules
  - gulpfile.js
  - LICENSE
  - package.json
  - package-lock.json
timezone: Europe/Copenhagen
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-responsive-image
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

collections:
  posts:
    output: true
    permalink: /posts/:title/
  employees:
    output: true
    permalink: /employees/:title/
  educations:
    output: true
    permalink: /educations/:categories/:title/
  conversations:
    output: true
    permalink: /conversations/:title/
  consultations:
    output: true
    permalink: /consultations/:title/
  internationals:
    output: true
    permalink: /internationals/:title/
  pages:
    output: true
    permalink: /:title/
  categories:
    output: true
    permalink: /educations/:name/
  testimonials:
    output: true
    permalink: /testimonials/:title/

defaults:
  -
    scope:
      type: posts
    values:
      layout: story
  -
    scope:
      type: employees
    values:
      layout: employee
  -
    scope:
      type: educations
    values:
      layout: education
  -
    scope:
      type: conversations
    values:
      layout: conversation
  -
    scope:
      type: consultations
    values:
      layout: consulting
  -
    scope:
      type: internationals
    values:
      layout: international
  -
    scope:
      type: categories
    values:
      layout: category
  -
    scope:
      type: testimonials
    values:
      layout: category
      
prose:
  rooturl: ''
  siteurl: 'www.copenhagencoaching.dk'
  relativeLinks: ''
  media: 'img/blog'
  ignore:
    - htmlproofer.sh
    - /_internationals
    - /_consultations
    - /_conversations
    - /_pages
    - /_testimonials
    - index.html
    - /portraits
    - robots.txt
    - favicon.ico
    - README.md
    - _dev_config.yml
    - _stage_config.yml
    - CNAME
    - CNAME.stage
    - devserve.sh
    - .gitignore
    - /img
    - /pages
    - _config.yml
    - /_layouts
    - /_includes
    - .circleci
    - /css
    - /js
    - /_sass
    - /_categories
  metadata:
    _posts:
      - name: "title"
        field:
          element: "text"
          label: "title"
      - name: "Author"
        field:
          element: "select"
          label: "Select Author"
          placeholder: "Choose Author"
          options:
            - name: "Lars Nyborg"
              value: "Lars Nyborg"
            - name: "Andreas Bering"
              value: "Andreas Bering"
            - name: "Anni Rosengren Korsbæk"
              value: "Anni Rosengren Korsbæk"
            - name: "Bianca Olivia Godske Røjbæk"
              value: "Bianca Olivia Godske Røjbæk"
            - name: "Frederikke Winther"
              value: "Frederikke Winther"
            - name: "Kim Gørtz"
              value: "Kim Gørtz"
            - name: "Marie Arnbak"
              value: "Marie Arnbak"
            - name: "Mette Mejhede"
              value: "Mette Mejhede"
            - name: "Morten Bertelsen"
              value: "Morten Bertelsen"
            - name: "Morten Paustian"
              value: "Morten Paustian"
            
      - name: "tags"
        field:
          element: "multiselect"
          label: "Add Tags"
          placeholder: "Choose Tags"
          alterable: true
          options:
            - name: "Coaching"
              value: "coaching"
            - name: "Ledelse"
              value: "ledelse"
            - name: "Events"
              value: "events"
            - name: "Kurser"
              value: "kurser"
    _educations:
      - name: "title"
        field:
          element: "text"
          label: "Titel"
      - name: "category"
        field:
          element: "select"
          label: "Vælg kategori"
          placeholder: "Vælg kategori"
          options:
            - name: "CCC Netværk"
              value: "ccc-netveark"
            - name: "Certificeringer"
              value: "certificeringer"
            - name: "Diplom i offentlig ledelse"
              value: "diplom-i-offentlig-ledelse"
            - name: "Filosofi"
              value: "filosofi"
            - name: "Lederskab"
              value: "lederskab"
            - name: "Master i business coaching"
              value: "master-i-business-coaching"
            - name: "Personlig udvikling og transition"
              value: "personlig-udvikling-og-transition"
            - name: "Proces og strategi"
              value: "proces-og-strategi"
    _employees:
      - name: "title"
        field:
          element: "text"
          label: "Navn"
      - name: "email"
        field:
          element: "text"
          label: "Email"
      - name: "call"
        field:
          element: "text"
          label: "Tlf."
      - name: "description"
        field:
          element: "text"
          label: "Beskrivelse"
      - name: "linkedin"
        field:
          element: "text"
          label: "LinkedIn profil"




responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html

  # [Optional, Default: 85]
  # Quality to use when resizing images.
  default_quality: 90

  # [Optional, Default: []]
  # An array of resize configuration objects. Each object must contain at least
  # a `width` value.
  sizes:
    - width: 255
    - width: 510
    - width: 1020

  # [Optional, Default: false]
  # Rotate resized images depending on their EXIF rotation attribute. Useful for
  # working with JPGs directly from digital cameras and smartphones
  auto_rotate: false

  # [Optional, Default: false]
  # Strip EXIF and other JPEG profiles. Helps to minimize JPEG size and win friends
  # at Google PageSpeed.
  strip: false

  # [Optional, Default: assets]
  # The base directory where assets are stored. This is used to determine the
  # `dirname` value in `output_path_format` below.
  base_path: assets

  # [Optional, Default: assets/resized/%{filename}-%{width}x%{height}.%{extension}]
  # The template used when generating filenames for resized images. Must be a
  # relative path.
  #
  # Parameters available are:
  #   %{dirname}     Directory of the file relative to `base_path` (assets/sub/dir/some-file.jpg => sub/dir)
  #   %{basename}    Basename of the file (assets/some-file.jpg => some-file.jpg)
  #   %{filename}    Basename without the extension (assets/some-file.jpg => some-file)
  #   %{extension}   Extension of the file (assets/some-file.jpg => jpg)
  #   %{width}       Width of the resized image
  #   %{height}      Height of the resized image
  #
  output_path_format: assets/responsive/%{width}/%{basename}

  # [Optional, Default: true]
  # Whether or not to save the generated assets into the source folder.
  save_to_source: false

  # [Optional, Default: false]
  # Cache the result of {% responsive_image %} and {% responsive_image_block %}
  # tags. See the "Caching" section of the README for more information.
  cache: false

  # [Optional, Default: []]
  # By default, only images referenced by the responsive_image and responsive_image_block
  # tags are resized. Here you can set a list of paths or path globs to resize other
  # images. This is useful for resizing images which will be referenced from stylesheets.
  extra_images:
    - assets/foo/bar.png
    - assets/bgs/*.png
    - assets/avatars/*.{jpeg,jpg}