title: Copenhagen Coaching Center - Coaching og uddannelse af ledere 
description: CCC tilbyder coaching og uddannelser målrettet det offentlige Danmark og erhvervslivet. Se vores mange tilbud om efteruddannelser og coachingløsninger her.
author: Copenhagencoaching.dk
url: https://www.copenhagencoaching.dk
image: /images/seo/ccc-seo-logo-dark.png
future: true

logo: /images/logo/ccc-logo-dark.png

sass:
  style: compressed

highlighter: rouge
exclude:
  - "*README.md"
  - gulpfile.js
  - LICENSE
  - .sass-cache/
timezone: Europe/Copenhagen
markdown: kramdown
permalink: /:categories/:title/

collections:
  posts:
    output: true
    permalink: /resonans/:categories/:title/
  employees:
    output: true
    permalink: /employees/:title/
  educations:
    output: true
    permalink: /uddannelser/:title/
  coachings:
    output: false
  pages:
    output: true
    permalink: /:title/
  texts:
    output: true
    permalink: /tekster/:title/
  publications:
    output: true
    permalink: /udgivelser/:title/
  landings:
    output: true
    permalink: /:title/
  consultings:
    output: true
    permalink: /konsulentydelser/:title/
  events:
    output: true
    permalink: /events/:title/

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
  -
    scope:
      type: employees
    values:
      layout: employee
  -
    scope:
      type: educations
    values:
      layout: course
  -
    scope:
      type: text
    values:
      layout: default
  -
    scope:
      type: publications
    values:
      layout: ousia
  -
    scope:
      type: landings
    values:
      layout: landing
  -
    scope:
      type: consultings
    values:
      layout: consultings
  -
    scope:
      type: events
    values:
      layout: event