collections_config:
  posts:
    name: Posts
    path: _posts
    schemas:
      blog-post:
        path: .cloudcannon/schemas/blog-post.md
        name: Blog post
        remove_extra_inputs: false
        hide_extra_inputs: true
        _enabled_editors:
          - content
        _inputs:
          $.title:
            label: Titel
          $.image:
            label: Billede
          $.description:
            label: Beskrivelse
          $.category:
            hidden: true
          $.tags:
            type: array
collection_groups:
  - heading: Content
    collections:
      - posts
paths:
  static: ''
  uploads: images
_inputs:
  template:
    hidden: true
