source: /
paths:
  uploads: uploads
  data: _data
  layouts: _layouts
  includes: _includes
collections_config:
  posts:
    schemas:
      default:
        path: /.cloudcannon/schemas/blog-post.md
    path: _posts
    output: true
    icon: notes
    create:
      path: >-
        [relative_base_path]/{date|year}-{date|month}-{date|day}-{title|slugify}.[ext]
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    _inputs:
      title:
        label: Titel
        comment: Indlæggets titel
      description:
        label: Beskrivelse
        comment: Kort beskrivelse af indlægget
      category:
        label: Katgeori
      podcast-id:
        label: Podcast ID (Kun hvis kategori er podcast)
        comment: Podcast afsnittets unikke id (Du finder det i Spodify linket til podcasten)
      video:
        label: Video (Kun hvis kategori er video)
        comment: Sti til videoen
        type: file
      subs:
        label: Undertekster (Kun hvis kategori er video)
        comment: Sti til underteksterne
        type: file
      image:
        label: Billede
  events:
    schemas:
      default:
        path: /.cloudcannon/schemas/event.md
    path: _events
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    _inputs:
      title:
        label: Titel
        comment: Eventets titel
      subtitle:
        label: Undetitel
      image:
        label: Billede
      date:
        label: Dato
        type: date
      infomode:
        label: Er eventet et infomøde?
        type: switch
      infomode-link:
        label: Hvilken uddannelse er infomødet for? (Kun hvis Infomøde er slået til)
        type: select
        options:
          values: collections.educations
      billetto:
        label: Kan man tilmelde sig via Billetto?
        type: switch
      billetto-nr:
        label: Billetto ID (Kun hvis Billetto er slået til)
        comment: Billetto event unik ID. Du kan finde det i billettos kontrolpanel.
      price:
        label: Pris
      place:
        label: lokation
      time:
        label: Tid
        type: text
  drafts:
    path: _drafts
    output: false
    icon: notes
    create:
      publish_to: posts
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  employees:
    path: _employees
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  educations:
    path: _educations
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  coachings:
    path: _coachings
    output: false
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  pages:
    path: _pages
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  texts:
    path: _texts
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  publications:
    path: _publications
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  landings:
    path: _landings
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  consultings:
    path: _consultings
    output: true
    icon: notes
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  categories:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
  tags:
    type: multiselect
    options:
      allow_create: true
      empty_type: array
    cascade: true
_select_data:
  sass:
    style: compressed
  config:
    - _config_cc.yml
_structures: {}
_editables: {}
data_config: {}
timezone: Europe/Copenhagen
