---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _texts
  label: Tekster
  create: none
  match: "**/*"
- type: directory
  path: _pages
  label: Sider
  create: none
  match: "**/*"
  exclude: "*.html"
- type: directory
  path: _fundament
  label: Fundament
  create: all
  match: "**/*"
- type: directory
  path: _internationals
  label: Internationals
  create: all
  match: "**/*"
- type: directory
  path: _consultations
  label: Consultations
  create: all
  match: "**/*"
- type: directory
  path: _coachings
  label: Coachings
  create: all
  match: "**/*"
- type: directory
  path: _educations
  label: Academy
  create: all
  match: "**/*"
  templates:
  - uddannelser
- type: directory
  path: _employees
  label: Employees
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
  templates:
  - uddannelser
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  install_dependencies_command: bundle install --path vendor/bundle
  preview_docker_image: forestryio/ruby:2.6
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
