---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _educations
  label: Uddannelser
  create: all
  match: "**/*"
- type: directory
  path: _posts
  label: Posts
  create: all
  match: "**/*"
upload_dir: images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: carolineolivia94/jekyll-plus-plus
  mount_path: "//app"
  working_dir: "/srv"
  instant_preview_command: " jekyll serve --config _config.yml,_dev_config.yml --watch"
